language: python
python:
  - "3.6"
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels bioconda
  
   - test $TRAVIS_BRANCH = "master" && conda install conda-build && bash recipe/conda_build.sh

  # Create and Activate the test environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION plex_stats --use-local
  - conda activate test-environment
 
script:
  plex_stats --help
  
